# Generated by Django 3.2.25 on 2026-09-04 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kolibri.core.coursework.models
import kolibri.core.fields
import kolibri.utils.time_utils
import morango.models.fields.uuids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kolibriauth', '0035_facilitydataset_picture_password_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', morango.models.fields.uuids.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('_morango_dirty_bit', models.BooleanField(default=True, editable=False)),
                ('_morango_source_id', models.CharField(editable=False, max_length=96)),
                ('_morango_partition', models.CharField(editable=False, max_length=128)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', kolibri.core.fields.DateTimeTzField(blank=True, null=True)),
                ('max_points', models.PositiveIntegerField(default=100)),
                ('allow_file_upload', models.BooleanField(default=True)),
                ('allow_text_submission', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now, editable=False)),
                ('date_modified', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='kolibriauth.collection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.facilitydataset')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('id', morango.models.fields.uuids.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('_morango_dirty_bit', models.BooleanField(default=True, editable=False)),
                ('_morango_source_id', models.CharField(editable=False, max_length=96)),
                ('_morango_partition', models.CharField(editable=False, max_length=128)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('date_created', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now, editable=False)),
                ('date_modified', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='kolibriauth.collection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.facilitydataset')),
            ],
            options={
                'ordering': ['-is_pinned', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', morango.models.fields.uuids.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('_morango_dirty_bit', models.BooleanField(default=True, editable=False)),
                ('_morango_source_id', models.CharField(editable=False, max_length=96)),
                ('_morango_partition', models.CharField(editable=False, max_length=128)),
                ('content', models.TextField()),
                ('is_endorsed', models.BooleanField(default=False)),
                ('date_created', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_replies_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.facilitydataset')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='coursework.discussionthread')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', morango.models.fields.uuids.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('_morango_dirty_bit', models.BooleanField(default=True, editable=False)),
                ('_morango_source_id', models.CharField(editable=False, max_length=96)),
                ('_morango_partition', models.CharField(editable=False, max_length=128)),
                ('text_content', models.TextField(blank=True, default='')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=kolibri.core.coursework.models.submission_file_path)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned')], default='submitted', max_length=20)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('submitted_at', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('graded_at', kolibri.core.fields.DateTimeTzField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coursework.assignment')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.facilitydataset')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_graded', to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'learner')},
            },
        ),
    ]
