# Generated by Django 3.2.25 on 2026-09-04 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursework', '0001_initial_coursework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionreply',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_replies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
