# Generated by Django 3.2.25 on 2026-09-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0002_update_coursework_authoring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
