# Generated by Django 3.2.25 on 2026-09-10 10:51

import django.db.models.deletion
import morango.models.fields.uuids
from django.db import migrations
from django.db import models

import kolibri.core.fields
import kolibri.utils.time_utils


class Migration(migrations.Migration):
    dependencies = [
        ("kolibriauth", "0036_facilitydataset_theme_field"),
        ("coursework", "0003_add_video_url_to_assignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnerIntervention",
            fields=[
                (
                    "id",
                    morango.models.fields.uuids.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "_morango_dirty_bit",
                    models.BooleanField(default=True, editable=False),
                ),
                ("_morango_source_id", models.CharField(editable=False, max_length=96)),
                (
                    "_morango_partition",
                    models.CharField(editable=False, max_length=128),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("high", "High Risk"),
                            ("moderate", "Moderate Risk"),
                            ("low", "Low Risk"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("reasons", kolibri.core.fields.JSONField(blank=True, default=list)),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("remedial_instruction", "Remedial Instruction"),
                            ("peer_tutoring", "Peer Tutoring & Study Buddy"),
                            ("parent_contact", "Parent / Guardian Conference"),
                            ("counseling", "Guidance Counseling Consultation"),
                            ("assignment_extension", "Assignment Deadline Extension"),
                            ("learning_materials", "Supplemental Modules & Reviewers"),
                        ],
                        default="remedial_instruction",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "target_date",
                    kolibri.core.fields.DateTimeTzField(blank=True, null=True),
                ),
                (
                    "date_created",
                    kolibri.core.fields.DateTimeTzField(
                        default=kolibri.utils.time_utils.local_now, editable=False
                    ),
                ),
                (
                    "date_modified",
                    kolibri.core.fields.DateTimeTzField(
                        default=kolibri.utils.time_utils.local_now
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions_logged",
                        to="kolibriauth.facilityuser",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_interventions",
                        to="kolibriauth.collection",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kolibriauth.facilitydataset",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions_received",
                        to="kolibriauth.facilityuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
